namespace SpieRibbon
{
    // GENERATED - do not hand-edit. Regenerated by deploy\Build-Package.ps1 from
    // deploy\VERSION.txt every time a package is built (that's what auto-bumps the patch
    // number). To do a "big" version bump, edit deploy\VERSION.txt directly, not this file.
    internal static class VersionInfo
    {
        public const string Label = "Beta v0.1.02";
    }
}
